export const fallbackData = {
    "data": [
        {
            "id": 140,
            "isincident": false,
            "address2": "Milpitas",
            "city": "Milpitas",
            "country": "United States",
            "state": "California",
            "pincode": "95035",
            "eventname": "GDT Corporate Dinner",
            "subtitle": "Fund Raising",
            "description": "Corporate Event Test",
            "title": "GDT Corporate Dinner",
            "contactphone": "1234567890",
            "contactemail": "rohit@gooddolphin.com",
            "secondarycontact": "0987654321",
            "startdatetime": "15/11/2024 07:15 PM",
            "enddatetime": "15/11/2024 10:00 PM",
            "address1": "East Calaveras Boulevard",
            "user_id": 209,
            "approvalrequired": true,
            "eventfees": 0,
            "iscompanyevent": 76,
            "maxage": "NA",
            "minage": "NA",
            "maxallowedparticipants": 100,
            "verifiedusersonly": false,
            "cityrestriction": [],
            "countryrestriction": [
                233
            ],
            "staterestriction": [],
            "gendercriteria": "NA",
            "categoryid": null,
            "categoryname": "NA",
            "imgurl": "https://ikarma.s3.us-east-2.amazonaws.com/nominations/media/images/b11b95b0-70b1-7012-28ed-3a57f98798da%3Aevent1-8AB3B545-7F22-40BD-9E4B-E4294EA012E1.jpeg%3A1731044770619",
            "join": true,
            "isprivilege": true,
            "peopleJoined": 55,
            "entry": "Free",
            "type": "Private"
        },
        {
            "id": 131,
            "isincident": false,
            "address2": "Milton",
            "city": "Milton",
            "country": "United States",
            "state": "Massachusetts",
            "pincode": "02186",
            "eventname": "Blood Donation Drive",
            "subtitle": "Join us at Holy Mary Hospital",
            "description": "Why Donate?\n\nEvery 2 seconds, someone needs blood.\nBlood cannot be manufactured; it can only come from generous donors like you.\nYour contribution ensures hospitals and patients have the life-saving resources they need.\nBe a hero—give the gift of life!",
            "title": "Blood Donation Drive",
            "contactphone": "1234567890",
            "contactemail": "balkrishna.meena@gooddolphin.com",
            "secondarycontact": "1234567890",
            "startdatetime": "30/10/2024 09:15 AM",
            "enddatetime": "30/10/2024 07:15 PM",
            "address1": "Reedsdale Road",
            "user_id": 207,
            "approvalrequired": false,
            "eventfees": null,
            "iscompanyevent": "NA",
            "maxage": 50,
            "minage": 18,
            "maxallowedparticipants": 250,
            "verifiedusersonly": false,
            "cityrestriction": [
                121915
            ],
            "countryrestriction": [
                233
            ],
            "staterestriction": [
                1433
            ],
            "gendercriteria": "NA",
            "categoryid": null,
            "categoryname": "NA",
            "imgurl": "https://ikarma.s3.us-east-2.amazonaws.com/nominations/media/images/b17b0590-b011-7052-7d02-9c3d94ca0325%3ADocuments117A49E2-1332-4514-A7D0-222A9DC89066.jpeg%3A1729709252588",
            "join": false,
            "isprivilege": false,
            "peopleJoined": 1,
            "entry": "Free",
            "type": "Private"
        },
        {
            "id": 130,
            "isincident": false,
            "address2": "4201 Ball Road",
            "city": "Cypress",
            "country": "United States",
            "state": "California",
            "pincode": "90630",
            "eventname": "Tree Plantation Drive",
            "subtitle": "An initiative of Eco Club",
            "description": "In our commitment to a greener future, we are excited to announce a Tree Plantation Drive! This initiative is a step towards reducing our carbon footprint, restoring biodiversity, and creating a healthier environment for generations to come.",
            "title": "Tree Plantation Drive",
            "contactphone": "1234567890",
            "contactemail": "balkrishna.meena@gooddolphin.com",
            "secondarycontact": "0987654321",
            "startdatetime": "01-11-2024 08:30 AM",
            "enddatetime": "01-11-2024 12:30 PM",
            "address1": "Nature Park",
            "user_id": 207,
            "approvalrequired": false,
            "eventfees": null,
            "iscompanyevent": 76,
            "maxage": "NA",
            "minage": "NA",
            "maxallowedparticipants": 100,
            "verifiedusersonly": false,
            "cityrestriction": [],
            "countryrestriction": [
                233
            ],
            "staterestriction": [
                1416
            ],
            "gendercriteria": "NA",
            "categoryid": null,
            "categoryname": "NA",
            "imgurl": "https://ikarma.s3.us-east-2.amazonaws.com/nominations/media/images/b17b0590-b011-7052-7d02-9c3d94ca0325%3ADocumentsC91E8F96-14B6-488B-9ED6-E8C282F721FA.jpeg%3A1729703048262",
            "join": false,
            "isprivilege": false,
            "peopleJoined": 1,
            "entry": "Free",
            "type": "Private"
        },
        {
            "id": 130,
            "isincident": false,
            "address2": "4201 Ball Road",
            "city": "Cypress",
            "country": "United States",
            "state": "California",
            "pincode": "90630",
            "eventname": "Tree Plantation Drive",
            "subtitle": "An initiative of Eco Club",
            "description": "In our commitment to a greener future, we are excited to announce a Tree Plantation Drive! This initiative is a step towards reducing our carbon footprint, restoring biodiversity, and creating a healthier environment for generations to come.",
            "title": "Tree Plantation Drive",
            "contactphone": "1234567890",
            "contactemail": "balkrishna.meena@gooddolphin.com",
            "secondarycontact": "0987654321",
            "startdatetime": "01-11-2024 08:30 AM",
            "enddatetime": "01-11-2024 12:30 PM",
            "address1": "Nature Park",
            "user_id": 207,
            "approvalrequired": false,
            "eventfees": null,
            "iscompanyevent": 76,
            "maxage": "NA",
            "minage": "NA",
            "maxallowedparticipants": 100,
            "verifiedusersonly": false,
            "cityrestriction": [],
            "countryrestriction": [
                233
            ],
            "staterestriction": [
                1416
            ],
            "gendercriteria": "NA",
            "categoryid": null,
            "categoryname": "NA",
            "imgurl": "https://ikarma.s3.us-east-2.amazonaws.com/nominations/media/images/b17b0590-b011-7052-7d02-9c3d94ca0325%3ADocumentsC91E8F96-14B6-488B-9ED6-E8C282F721FA.jpeg%3A1729703048262",
            "join": false,
            "isprivilege": false,
            "peopleJoined": 1,
            "entry": "Free",
            "type": "Private"
        },
        {
            "id": 130,
            "isincident": false,
            "address2": "4201 Ball Road",
            "city": "Cypress",
            "country": "United States",
            "state": "California",
            "pincode": "90630",
            "eventname": "Tree Plantation Drive",
            "subtitle": "An initiative of Eco Club",
            "description": "In our commitment to a greener future, we are excited to announce a Tree Plantation Drive! This initiative is a step towards reducing our carbon footprint, restoring biodiversity, and creating a healthier environment for generations to come.",
            "title": "Tree Plantation Drive",
            "contactphone": "1234567890",
            "contactemail": "balkrishna.meena@gooddolphin.com",
            "secondarycontact": "0987654321",
            "startdatetime": "01-11-2024 08:30 AM",
            "enddatetime": "01-11-2024 12:30 PM",
            "address1": "Nature Park",
            "user_id": 207,
            "approvalrequired": false,
            "eventfees": null,
            "iscompanyevent": 76,
            "maxage": "NA",
            "minage": "NA",
            "maxallowedparticipants": 100,
            "verifiedusersonly": false,
            "cityrestriction": [],
            "countryrestriction": [
                233
            ],
            "staterestriction": [
                1416
            ],
            "gendercriteria": "NA",
            "categoryid": null,
            "categoryname": "NA",
            "imgurl": "https://ikarma.s3.us-east-2.amazonaws.com/nominations/media/images/b17b0590-b011-7052-7d02-9c3d94ca0325%3ADocumentsC91E8F96-14B6-488B-9ED6-E8C282F721FA.jpeg%3A1729703048262",
            "join": false,
            "isprivilege": false,
            "peopleJoined": 1,
            "entry": "Free",
            "type": "Private"
        }
    ],
    "message": "get Data successfully",
    "resCode": 1
};
  